{{- if .Values.webhook.enable }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: tf-state-rescuer-validating-webhook-configuration
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certmanager.enable }}
    cert-manager.io/inject-ca-from: "{{ $.Release.Namespace }}/serving-cert"
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
webhooks:
  - name: vstaterescue-v1.kb.io
    clientConfig:
      service:
        name: tf-state-rescuer-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-terraform-hammadzf-github-io-v1-staterescue
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - terraform.hammadzf.github.io
        apiVersions:
          - v1
        resources:
          - staterescues
{{- end }}
