apiVersion: terraform.hammadzf.github.io/v1
kind: StateRescue
metadata:
  labels:
    app.kubernetes.io/name: tf-state-rescuer
    app.kubernetes.io/managed-by: kustomize
  name: =staterescue-invalid-name
spec:
  stateSecretName: "terraform-state-default-state"
